#!/usr/bin/env bash
# PORT-NOTE (#1444): release-backlog nudge distributed via the three-role-model plugin by EXPLICIT operator
#   decision (#1444) — it is NOT a 3-role SHIP gate, but travels with the plugin so every consuming repo
#   inherits the batch-release boundary tap. DO NOT PRUNE from the synced set. Generated by
#   scripts/sync-three-role-plugin.mjs; never hand-edit. The nudge names scripts/cut-release.sh generically —
#   a repo without that helper still acts on the nudge (run /ship Stage 7).
# Smoke/acceptance harness for hooks/release-backlog-nudge.sh.
# Exits 0 iff every AC passes. Final line: "PASS=N FAIL=M".
# Parameterized by RELEASE_BACKLOG_HOOK so the red-first receipt generator can point
# it at a surgically-broken copy and watch a case flip to FAIL (RED), then GREEN.
set -u

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
HOOK="${RELEASE_BACKLOG_HOOK:-$SCRIPT_DIR/../release-backlog-nudge.sh}"

if [ ! -f "$HOOK" ]; then echo "FATAL: hook not found at $HOOK" >&2; exit 1; fi

PASS=0; FAIL=0; FAILED=()
ok() { PASS=$((PASS+1)); printf '  [PASS] %s\n' "$1"; }
no() { FAIL=$((FAIL+1)); FAILED+=("$1"); printf '  [FAIL] %s\n' "$1"; }

days_ago_iso() {
  date -u -v-"${1}"d +%Y-%m-%dT%H:%M:%S 2>/dev/null || date -u -d "-${1} days" +%Y-%m-%dT%H:%M:%S
}

# Build a git repo named $1 with: 1 tagged commit (v0.1.0, committed $2 days ago)
# then $3 additional (substantive) commits on top. Prints the repo path.
mk_repo() {
  local name="$1" tag_days_ago="$2" extra="$3"
  local root; root="$(mktemp -d -t "rbn-${name}-XXXXXX")"
  local repo="$root/$name"
  mkdir -p "$repo"
  local d; d="$(days_ago_iso "$tag_days_ago")"
  (
    cd "$repo"
    git init -q
    git -c user.email=t@t -c user.name=t commit -q --allow-empty -m "base" --date="$d"
    GIT_COMMITTER_DATE="$d" git -c user.email=t@t -c user.name=t commit -q --allow-empty --amend -m "base" --date="$d" >/dev/null 2>&1
    git tag v0.1.0
    local i=0
    while [ "$i" -lt "$extra" ]; do
      git -c user.email=t@t -c user.name=t commit -q --allow-empty -m "c$i"
      i=$((i+1))
    done
  )
  printf '%s\n' "$repo"
}

# Build a repo named $1 (tag $2 days ago) with one commit per SUBJECT ($3..). Prints path.
mk_repo_msgs() {
  local name="$1" tag_days_ago="$2"; shift 2
  local root; root="$(mktemp -d -t "rbn-${name}-XXXXXX")"
  local repo="$root/$name"; mkdir -p "$repo"
  local d subj; d="$(days_ago_iso "$tag_days_ago")"
  (
    cd "$repo"
    git init -q
    git -c user.email=t@t -c user.name=t commit -q --allow-empty -m "base" --date="$d"
    GIT_COMMITTER_DATE="$d" git -c user.email=t@t -c user.name=t commit -q --allow-empty --amend -m "base" --date="$d" >/dev/null 2>&1
    git tag v0.1.0
    for subj in "$@"; do
      git -c user.email=t@t -c user.name=t commit -q --allow-empty -m "$subj"
    done
  )
  printf '%s\n' "$repo"
}

# Build a repo at an EXPLICIT absolute path $1 (tag $2 days ago) with one commit per SUBJECT ($3..).
mk_repo_at() {
  local repo="$1" tag_days_ago="$2"; shift 2
  local d subj; mkdir -p "$repo"; d="$(days_ago_iso "$tag_days_ago")"
  (
    cd "$repo"
    git init -q
    git -c user.email=t@t -c user.name=t commit -q --allow-empty -m "base" --date="$d"
    GIT_COMMITTER_DATE="$d" git -c user.email=t@t -c user.name=t commit -q --allow-empty --amend -m "base" --date="$d" >/dev/null 2>&1
    git tag v0.1.0
    for subj in "$@"; do
      git -c user.email=t@t -c user.name=t commit -q --allow-empty -m "$subj"
    done
  )
}

# Run the hook against a cwd with env (SessionStart payload, real HOME). Sets OUT.
run_hook() {
  local cwd="$1" envline="$2"
  local payload; payload="$(node -e "process.stdout.write(JSON.stringify({hook_event_name:'SessionStart',cwd:process.argv[1]}))" "$cwd")"
  OUT="$(printf '%s' "$payload" | env -i HOME="$HOME" PATH="$PATH" PWD="$cwd" $envline bash "$HOOK" 2>/dev/null)"
}

# Run the hook with a Stop payload carrying session_id + stop_hook_active, and an
# overridable HOME (for marker isolation + the generic ~/coding_projects/ default).
# Args: cwd envline session_id stop_active(true|"") [home]. Sets OUT.
run_hook_stop() {
  local cwd="$1" envline="$2" sid="$3" sa="$4" home="${5:-$HOME}"
  local payload
  payload="$(node -e "process.stdout.write(JSON.stringify({hook_event_name:'Stop',cwd:process.argv[1],session_id:process.argv[2],stop_hook_active:(process.argv[3]==='true')}))" "$cwd" "$sid" "$sa")"
  OUT="$(printf '%s' "$payload" | env -i HOME="$home" PATH="$PATH" PWD="$cwd" $envline bash "$HOOK" 2>/dev/null)"
}

has_nudge() { case "$OUT" in *_NUDGE:*) return 0;; *) return 1;; esac; }

# ── Existing coarse-band + gate ACs (regression) ─────────────────────────────────────

# AC-1: gap >= COMMITS threshold -> coarse nudge.
r="$(mk_repo allow 0 5)"
run_hook "$r" "RELEASE_BACKLOG_REPOS=allow RELEASE_BACKLOG_COMMITS=3 RELEASE_BACKLOG_DAYS=999"
if has_nudge && case "$OUT" in *"5 commits"*) true;; *) false;; esac; then ok "AC-1 commit-threshold trips a coarse nudge"; else no "AC-1 commit-threshold trips a nudge (out: $OUT)"; fi

# AC-2: gap and days both below threshold, fine band suppressed (MIN high) -> no nudge.
r="$(mk_repo allow 1 2)"
run_hook "$r" "RELEASE_BACKLOG_REPOS=allow RELEASE_BACKLOG_COMMITS=30 RELEASE_BACKLOG_DAYS=10 RELEASE_BACKLOG_MIN_SUBSTANTIVE=99"
if has_nudge; then no "AC-2 under both thresholds (fine suppressed) stays quiet (out: $OUT)"; else ok "AC-2 under both thresholds (fine suppressed) stays quiet"; fi

# AC-3: days >= DAYS threshold with low gap -> coarse nudge.
r="$(mk_repo allow 30 1)"
run_hook "$r" "RELEASE_BACKLOG_REPOS=allow RELEASE_BACKLOG_COMMITS=999 RELEASE_BACKLOG_DAYS=10"
if has_nudge; then ok "AC-3 day-threshold trips a coarse nudge even with a low commit gap"; else no "AC-3 day-threshold trips a nudge (out: $OUT)"; fi

# AC-4: repo not in allowlist -> no nudge.
r="$(mk_repo other 0 50)"
run_hook "$r" "RELEASE_BACKLOG_REPOS=ai-brain RELEASE_BACKLOG_COMMITS=3 RELEASE_BACKLOG_DAYS=1"
if has_nudge; then no "AC-4 non-allowlist repo stays quiet (out: $OUT)"; else ok "AC-4 non-allowlist repo stays quiet"; fi

# AC-5: a secondary worktree -> no nudge (only the primary clone nudges).
r="$(mk_repo allow 0 50)"
wt="$r-wt"
( cd "$r" && git worktree add -q "$wt" -b wtbranch HEAD ) >/dev/null 2>&1
run_hook "$wt" "RELEASE_BACKLOG_REPOS=allow RELEASE_BACKLOG_COMMITS=3 RELEASE_BACKLOG_DAYS=1"
if has_nudge; then no "AC-5 secondary worktree stays quiet (out: $OUT)"; else ok "AC-5 secondary worktree stays quiet"; fi

# AC-6: no tags -> no nudge (fail-open).
r="$(mktemp -d -t rbn-notag-XXXXXX)/allow"; mkdir -p "$r"
( cd "$r" && git init -q && git -c user.email=t@t -c user.name=t commit -q --allow-empty -m base )
run_hook "$r" "RELEASE_BACKLOG_REPOS=allow RELEASE_BACKLOG_COMMITS=0 RELEASE_BACKLOG_DAYS=0"
if has_nudge; then no "AC-6 no-tags repo stays quiet (out: $OUT)"; else ok "AC-6 no-tags repo stays quiet"; fi

# AC-7: RELEASE_BACKLOG_OFF=1 -> no nudge (coarse backlog).
r="$(mk_repo allow 0 50)"
run_hook "$r" "RELEASE_BACKLOG_REPOS=allow RELEASE_BACKLOG_COMMITS=3 RELEASE_BACKLOG_DAYS=1 RELEASE_BACKLOG_OFF=1"
if has_nudge; then no "AC-7 RELEASE_BACKLOG_OFF=1 silences (out: $OUT)"; else ok "AC-7 RELEASE_BACKLOG_OFF=1 silences"; fi

# AC-8: clean stdout contract — non-git cwd never errors / never prints.
r="$(mktemp -d -t rbn-nogit-XXXXXX)"
run_hook "$r" "RELEASE_BACKLOG_REPOS=allow RELEASE_BACKLOG_COMMITS=0 RELEASE_BACKLOG_DAYS=0"
if [ -z "$OUT" ]; then ok "AC-8 non-git cwd is silent + fail-open"; else no "AC-8 non-git cwd is silent (out: $OUT)"; fi

# AC-9: cwd is a SUBDIR of the primary clone — must STILL nudge (symlinked-path-safe regression).
r="$(mk_repo allow 0 5)"
mkdir -p "$r/sub/deeper"
run_hook "$r/sub/deeper" "RELEASE_BACKLOG_REPOS=allow RELEASE_BACKLOG_COMMITS=3 RELEASE_BACKLOG_DAYS=999"
if has_nudge; then ok "AC-9 nudges from a subdir of the primary clone (symlinked-path-safe)"; else no "AC-9 nudges from a subdir (out: $OUT)"; fi

# ── New #1444 fine-band + generic-default + marker ACs ───────────────────────────────

# AC-10 (fine band fires): 1 substantive commit below coarse -> a once-per-session fine nudge.
H="$(mktemp -d -t rbn-h10-XXXXXX)"; mkdir -p "$H/.claude"
r="$(mk_repo_msgs finefire 0 'feat: real work (#200)')"
run_hook_stop "$r" "RELEASE_BACKLOG_REPOS=finefire RELEASE_BACKLOG_COMMITS=30 RELEASE_BACKLOG_DAYS=10" "sess-A" "" "$H"
if has_nudge && case "$OUT" in *"unreleased commit"*) true;; *) false;; esac; then ok "AC-10 fine band fires on >=1 substantive commit below coarse"; else no "AC-10 fine band fires (out: $OUT)"; fi

# AC-11 (noise excluded): backlog of ONLY chore(cairn) store-sync/heartbeat -> silent.
H="$(mktemp -d -t rbn-h11-XXXXXX)"; mkdir -p "$H/.claude"
r="$(mk_repo_msgs noisy 0 'chore(cairn): store sync aaaa' 'chore(cairn): heartbeat bbbb')"
run_hook_stop "$r" "RELEASE_BACKLOG_REPOS=noisy RELEASE_BACKLOG_COMMITS=30 RELEASE_BACKLOG_DAYS=10" "sess-B" "" "$H"
if has_nudge; then no "AC-11 noise-only backlog stays quiet (out: $OUT)"; else ok "AC-11 noise-only backlog stays quiet (store sync/heartbeat excluded)"; fi

# AC-12 (block-once marker): first Stop nudges, second identical Stop is silent, stop_hook_active silent.
H="$(mktemp -d -t rbn-h12-XXXXXX)"; mkdir -p "$H/.claude"
r="$(mk_repo_msgs blockonce 0 'feat: thing (#201)')"
run_hook_stop "$r" "RELEASE_BACKLOG_REPOS=blockonce RELEASE_BACKLOG_COMMITS=30 RELEASE_BACKLOG_DAYS=10" "sess-C" "" "$H"
first=0; has_nudge && first=1
run_hook_stop "$r" "RELEASE_BACKLOG_REPOS=blockonce RELEASE_BACKLOG_COMMITS=30 RELEASE_BACKLOG_DAYS=10" "sess-C" "" "$H"
second=1; has_nudge || second=0
run_hook_stop "$r" "RELEASE_BACKLOG_REPOS=blockonce RELEASE_BACKLOG_COMMITS=30 RELEASE_BACKLOG_DAYS=10" "sess-C" "true" "$H"
third=1; has_nudge || third=0
if [ "$first" -eq 1 ] && [ "$second" -eq 0 ] && [ "$third" -eq 0 ]; then ok "AC-12 block-once: fires first, silent on repeat + stop_hook_active"; else no "AC-12 block-once (first=$first second=$second third=$third)"; fi

# AC-13 (generic default — NEITHER-fire hole fixed): unlisted repo under ~/coding_projects/ fires.
H="$(mktemp -d -t rbn-h13-XXXXXX)"; mkdir -p "$H/.claude"
gr="$H/coding_projects/genrepo"
mk_repo_at "$gr" 0 'feat: generic work (#202)'
run_hook_stop "$gr" "" "sess-D" "" "$H"
if has_nudge; then ok "AC-13 generic default: unlisted ~/coding_projects/ repo fires (RELEASE_BACKLOG_REPOS unset)"; else no "AC-13 generic default fires (out: $OUT)"; fi

# AC-14 (fine-band kill-switch): RELEASE_BACKLOG_OFF=1 silences a fine backlog.
H="$(mktemp -d -t rbn-h14-XXXXXX)"; mkdir -p "$H/.claude"
r="$(mk_repo_msgs finekill 0 'feat: x (#203)')"
run_hook_stop "$r" "RELEASE_BACKLOG_REPOS=finekill RELEASE_BACKLOG_OFF=1" "sess-E" "" "$H"
if has_nudge; then no "AC-14 fine-band kill-switch silences (out: $OUT)"; else ok "AC-14 fine-band kill-switch silences"; fi

# AC-15 (coarse regression — every Stop, NOT marker-gated): >=COMMITS fires on both Stops.
H="$(mktemp -d -t rbn-h15-XXXXXX)"; mkdir -p "$H/.claude"
r="$(mk_repo coarsereg 0 35)"
run_hook_stop "$r" "RELEASE_BACKLOG_REPOS=coarsereg RELEASE_BACKLOG_COMMITS=30 RELEASE_BACKLOG_DAYS=999" "sess-F" "" "$H"
c1=0; has_nudge && c1=1
run_hook_stop "$r" "RELEASE_BACKLOG_REPOS=coarsereg RELEASE_BACKLOG_COMMITS=30 RELEASE_BACKLOG_DAYS=999" "sess-F" "" "$H"
c2=0; has_nudge && c2=1
if [ "$c1" -eq 1 ] && [ "$c2" -eq 1 ]; then ok "AC-15 coarse band fires every Stop (not marker-gated)"; else no "AC-15 coarse every-Stop (c1=$c1 c2=$c2)"; fi

echo ""
echo "PASS=$PASS FAIL=$FAIL"
if [ "$FAIL" -gt 0 ]; then printf '  - %s\n' "${FAILED[@]}"; exit 1; fi
exit 0
