#!/usr/bin/env bash
# PORT-NOTE (#1444): release-backlog nudge distributed via the three-role-model plugin by EXPLICIT operator
#   decision (#1444) — it is NOT a 3-role SHIP gate, but travels with the plugin so every consuming repo
#   inherits the batch-release boundary tap. DO NOT PRUNE from the synced set. Generated by
#   scripts/sync-three-role-plugin.mjs; never hand-edit. The nudge names scripts/cut-release.sh generically —
#   a repo without that helper still acts on the nudge (run /ship Stage 7).
# Stop hook — release-backlog tripwire (two severity bands, generic across repos).
#
# Surfaces a single `_NUDGE:` line at a session/lane boundary (Stop) when the
# *primary* clone of a git repo has unreleased commits since its most recent
# vX.Y.Z tag. Without this, a release deferral leaves no visible trace, so
# deferrals silently compound: incident 2026-06-08 — 75 commits / 6 days
# accumulated unreleased since v0.55.0 because each ship deferred the release
# with no backlog visibility. (#1444: Option A — land lean per-ticket, cut ONE
# release ceremony per session/lane boundary; this is the boundary tap.)
#
# TWO BANDS (mutually exclusive by threshold, ONE hook, ONE noise regex, ONE marker):
#   - COARSE (existing, back-compat): SUBSTANTIVE >= RELEASE_BACKLOG_COMMITS OR
#     DAYS >= RELEASE_BACKLOG_DAYS -> nudge EVERY Stop ("you've deferred for weeks").
#   - FINE (new, #1444): 1 <= SUBSTANTIVE < RELEASE_BACKLOG_COMMITS AND
#     DAYS < RELEASE_BACKLOG_DAYS -> nudge ONCE per session per <session>:<repo>:<tag>
#     (marker de-dup; firing every Stop from the first substantive commit would be
#     far too noisy). Re-fires only after a new tag is cut (state changes) or a new
#     session starts. This is the "ONE ceremony per session boundary" tap.
#
# Class: mechanical (Rule 17 / feedback_mechanical_hook_both_ends_verifiable) — both
# ends are booleans over objective git state:
#   - recurrence condition: (substantive commits since last tag in a band's range)
#   - fix-landed signal:     cutting a new vX.Y.Z tag resets both bands below threshold
# A Stop nudge (not a hard block) is the correct lever: you cannot "block" the
# absence of a release, and a hard ship-block would be too aggressive. The marker is
# the "closed" direction — it forces at-least-one visible tap per session on a genuine
# positive; the lever is visibility, not a hard block.
#
# NOISE exclusion (real-data correctness): bookkeeping commits matching
# RELEASE_NOISE_RE (default `^chore\(cairn\): (store sync|heartbeat)`) do NOT count —
# a backlog of pure store-sync/heartbeat chores is not a release-worthy backlog.
#
# GENERIC across repos (#1444): when RELEASE_BACKLOG_REPOS is UNSET, nudge for ANY
# primary clone under ~/coding_projects/ (trailing-slash anchored, mirroring
# rule-12-guard.sh's inverted default). RELEASE_BACKLOG_REPOS is a NARROWING override.
#
# Environment contract:
#   RELEASE_BACKLOG_REPOS          space-separated repo basenames to NARROW to. UNSET
#                                  => every primary clone under ~/coding_projects/.
#   RELEASE_BACKLOG_COMMITS        coarse commit threshold; default 30.
#   RELEASE_BACKLOG_DAYS           coarse day threshold; default 10.
#   RELEASE_BACKLOG_MIN_SUBSTANTIVE fine-band floor; default 1.
#   RELEASE_NOISE_RE               ERE of bookkeeping-noise subjects to exclude from the count.
#   RELEASE_BACKLOG_MARKER_TTL_DAYS marker age-prune TTL in days; default 30.
#   RELEASE_BACKLOG_OFF=1          silence entirely.
#
# Read-only and fail-OPEN: any error (not a git repo, no tags, parse failure) results
# in exit 0 with no output. Never blocks or slows a session stop. Counts against local
# HEAD only (a Stop hook must never `git fetch`) — an unpushed local commit still counts
# as unreleased, which is the correct advisory direction.

# #1543 — source the shared write-time bypass-audit writer (hook_log_bypass), if not already.
# This file is ALSO ported to the public three-role-model plugin (Population B), which does NOT ship
# lib-hook-override.sh — every call site below is `type`-guarded so a plugin install (no wrapper lib
# present) silently no-ops instead of erroring; ai-brain installs (lib present) log normally.
OVERRIDE_LIB="$(dirname "${BASH_SOURCE[0]}")/lib-hook-override.sh"
[ -f "$OVERRIDE_LIB" ] && . "$OVERRIDE_LIB"
set +e

if [ "${RELEASE_BACKLOG_OFF:-}" = "1" ]; then
  type hook_log_bypass >/dev/null 2>&1 && hook_log_bypass "release-backlog-nudge" "RELEASE_BACKLOG_OFF" "PERMIT" "${INPUT:-}"
  exit 0
fi

# RELEASE_BACKLOG_REPOS UNSET => generic (all ~/coding_projects/ primary clones).
# SET (even empty) => narrow to the listed basenames.
if [ -n "${RELEASE_BACKLOG_REPOS+x}" ]; then
  REPOS_SET=1
  REPOS="$RELEASE_BACKLOG_REPOS"
else
  REPOS_SET=0
  REPOS=""
fi
COMMITS_THRESHOLD="${RELEASE_BACKLOG_COMMITS:-30}"
DAYS_THRESHOLD="${RELEASE_BACKLOG_DAYS:-10}"
MIN_SUBSTANTIVE="${RELEASE_BACKLOG_MIN_SUBSTANTIVE:-1}"
RELEASE_NOISE_RE="${RELEASE_NOISE_RE:-^chore\(cairn\): (store sync|heartbeat)}"
TTL_DAYS="${RELEASE_BACKLOG_MARKER_TTL_DAYS:-30}"

# Resolve cwd + session_id + stop_hook_active from the Stop JSON payload, else PWD.
INPUT="$(cat 2>/dev/null)"
CWD=""; SESSION_ID=""; STOP_ACTIVE=""
if [ -n "$INPUT" ] && command -v node >/dev/null 2>&1; then
  META="$(printf '%s' "$INPUT" | node -e "
let d='';process.stdin.on('data',c=>d+=c);
process.stdin.on('end',()=>{try{const j=JSON.parse(d);process.stdout.write([j.cwd||'',j.session_id||'',(j.stop_hook_active?'true':'')].join('\n'));}catch(e){process.stdout.write('');}});
" 2>/dev/null)"
  CWD="$(printf '%s' "$META" | sed -n '1p')"
  SESSION_ID="$(printf '%s' "$META" | sed -n '2p')"
  STOP_ACTIVE="$(printf '%s' "$META" | sed -n '3p')"
fi
[ -z "$CWD" ] && CWD="$PWD"

# Honor stop_hook_active — a Stop-hook continuation loop: nudge at most once per turn-end.
[ "$STOP_ACTIVE" = "true" ] && exit 0

cd "$CWD" 2>/dev/null || exit 0

# Only act in a real git repo. Ask git for BOTH paths as absolute in ONE call
# (--path-format=absolute, git 2.31+) so the primary-vs-worktree equality test is
# string-comparable. Do NOT hand-roll abs() via `cd … && pwd`: from a SUBDIR of
# the primary clone, --git-dir returns an absolute path while --git-common-dir
# returns a relative one, and pwd-resolving only the relative side dereferences a
# symlinked path component (macOS /var -> /private/var) so the two diverge and the
# equality check wrongly fails — silencing the tripwire in any subdir of a repo
# under a symlinked path. Letting git format both identically avoids that.
GIT_PATHS="$(GIT_OPTIONAL_LOCKS=0 git rev-parse --path-format=absolute --git-dir --git-common-dir 2>/dev/null)"
GIT_DIR="${GIT_PATHS%%$'\n'*}"
GIT_COMMON_DIR="${GIT_PATHS##*$'\n'}"
[ -z "$GIT_DIR" ] || [ -z "$GIT_COMMON_DIR" ] && exit 0

# Only the PRIMARY clone (git-dir == git-common-dir, both absolute). Worktrees
# skip — avoids a duplicate nudge per active worktree.
[ "$GIT_DIR" != "$GIT_COMMON_DIR" ] && exit 0

# Repo basename = the primary clone's directory name (parent of --git-common-dir,
# which is "<primary>/.git").
REPO_PARENT="${GIT_COMMON_DIR%/*}"
REPO_BASENAME="${REPO_PARENT##*/}"

# Allowlist gate.
if [ "$REPOS_SET" -eq 1 ]; then
  # Narrowing override: basename must be in the explicit list.
  ALLOWED=0
  for r in $REPOS; do [ "$r" = "$REPO_BASENAME" ] && ALLOWED=1 && break; done
  [ "$ALLOWED" -ne 1 ] && exit 0
else
  # Generic default: any primary clone under ~/coding_projects/ (trailing-slash
  # anchored so ~/coding_projects-evil/x does NOT match). Resolve BOTH sides to
  # their physical path (pwd -P) so a symlinked prefix (macOS /var -> /private/var)
  # compares equal.
  CODING_ROOT="$(cd "$HOME/coding_projects" 2>/dev/null && pwd -P 2>/dev/null)"
  [ -z "$CODING_ROOT" ] && exit 0
  REPO_PARENT_R="$(cd "$REPO_PARENT" 2>/dev/null && pwd -P 2>/dev/null)"
  [ -z "$REPO_PARENT_R" ] && exit 0
  case "$REPO_PARENT_R/" in
    "$CODING_ROOT/"*) : ;;
    *) exit 0;;
  esac
fi

# Most recent vX.Y.Z tag reachable from HEAD. No tags -> nothing to compare (silent).
LAST_TAG="$(GIT_OPTIONAL_LOCKS=0 git describe --tags --match 'v[0-9]*' --abbrev=0 2>/dev/null)"
[ -z "$LAST_TAG" ] && exit 0

# SUBSTANTIVE commits since the tag: local HEAD (no fetch), EXCLUDING noise subjects.
SUBSTANTIVE="$(GIT_OPTIONAL_LOCKS=0 git log "${LAST_TAG}..HEAD" --no-merges --format='%s' 2>/dev/null \
  | grep -v '^[[:space:]]*$' | grep -Evc "$RELEASE_NOISE_RE")"
case "$SUBSTANTIVE" in ''|*[!0-9]*) SUBSTANTIVE=0;; esac

# Days since the tag's commit date.
TAG_EPOCH="$(GIT_OPTIONAL_LOCKS=0 git log -1 --format=%ct "$LAST_TAG" 2>/dev/null)"
NOW_EPOCH="$(date +%s 2>/dev/null)"
DAYS=0
case "$TAG_EPOCH$NOW_EPOCH" in
  *[!0-9]*|'') DAYS=0;;
  *) [ "$NOW_EPOCH" -ge "$TAG_EPOCH" ] && DAYS=$(( (NOW_EPOCH - TAG_EPOCH) / 86400 ));;
esac

# ── COARSE band (every Stop, back-compat) ────────────────────────────────────────────
if [ "$SUBSTANTIVE" -ge "$COMMITS_THRESHOLD" ] || [ "$DAYS" -ge "$DAYS_THRESHOLD" ]; then
  printf '_NUDGE: %s is %s commits / %sd past %s — cut a release (scripts/cut-release.sh, or /ship Stage 7: bump package.json + CHANGELOG + tag v<next>). Silence: RELEASE_BACKLOG_OFF=1_\n' \
    "$REPO_BASENAME" "$SUBSTANTIVE" "$DAYS" "$LAST_TAG"
  exit 0
fi

# ── FINE band (once per session per <session>:<repo>:<tag>) ───────────────────────────
if [ "$SUBSTANTIVE" -ge "$MIN_SUBSTANTIVE" ]; then
  MARKER_DIR="$HOME/.claude/.release-backlog-nudge"
  KEY="${SESSION_ID:-nosession}:${REPO_BASENAME}:${LAST_TAG}"
  SAFE_KEY="$(printf '%s' "$KEY" | tr -c 'A-Za-z0-9._-' '_')"
  MARKER="$MARKER_DIR/$SAFE_KEY"
  if [ -n "$MARKER_DIR" ] && mkdir -p "$MARKER_DIR" 2>/dev/null; then
    # Age-prune so the marker dir can't grow unbounded.
    case "$TTL_DAYS" in ''|*[!0-9]*) TTL_DAYS=30;; esac
    find "$MARKER_DIR" -type f -mtime +"$TTL_DAYS" -exec rm -f {} + 2>/dev/null || true
    # Already nudged for this <session>:<repo>:<tag> state -> silent (block-once).
    [ -f "$MARKER" ] && exit 0
    : > "$MARKER" 2>/dev/null || true
  fi
  printf '_NUDGE: %s has %s unreleased commit(s) since %s — cut a release at this session boundary (scripts/cut-release.sh, or /ship Stage 7). Silence: RELEASE_BACKLOG_OFF=1_\n' \
    "$REPO_BASENAME" "$SUBSTANTIVE" "$LAST_TAG"
  exit 0
fi

exit 0
